#!/bin/sh
#
# rc.halt       This file is executed by init when it goes into runlevel
#               0 (halt) or runlevel 6 (reboot). It kills all processes,
#               unmounts file systems and then either halts or reboots.
#
# Author:       Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#               Modified for RHS Linux by Damien Neil
#

export NOLOCALE=1

WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/init.d/functions

HALTCMD=
SourceIfNotEmpty /etc/sysconfig/halt
[ -x "$HALTCMD" ] || HALTCMD=/sbin/poweroff

case "${INIT_HALT-}" in
	HALT) HALTCMD=/sbin/halt ;;
	POWEROFF) HALTCMD=/sbin/poweroff ;;
esac

unset TEXTDOMAIN TEXTDOMAINDIR

unset action

action_begin_msg()
{
	[ -z "$*" ] || printf '%s ' "$*"
}

action_end_msg()
{
	local rc=$1
	if [ "$BOOTUP" = color ]; then
		[ $rc = 0 ] && echo_success || echo_failure
	fi
	echo
}

action_passed_msg()
{
	[ "$BOOTUP" != color ] ||
		echo_passed
	echo
}

action()
{
	action_begin_msg "$1"
	shift
	$*
	local rc=$?
	action_end_msg "$rc"
	return $rc
}

sendsigs()
{
	action_begin_msg 'Asking all remaining processes to terminate'
	killall5 -15
	local rc=$?
	if [ "$rc" = 2 ]; then
		action_passed_msg
		return
	else
		action_end_msg "$rc"
	fi

	local seq=5
	if [ "$rc" = 0 ]; then
		for seq in 1 2 3 4 5; do
			killall5 -18 || break
			sleep 1
		done
	fi

	[ "$seq" = 5 ] || return 0
	action_begin_msg 'Killing all remaining processes'
	killall5 -9
	rc=$?
	if [ "$rc" = 2 ]; then
		action_passed_msg
	else
		action_end_msg "$rc"
	fi
}

# See how we were called.
case "$0" in
	*halt)
		message='The system is halted'
		command="$HALTCMD"
		;;
	*poweroff)
		message='The system is halted; trying to turn off the power'
		command=/sbin/poweroff
		;;
	*reboot)
		message='Please stand by while rebooting the system...'
		command=/sbin/reboot
		;;
	*)
		msg_usage "${0##*/}: call me as \"halt\", \"reboot\" or \"poweroff\" please!"
		exit 1
		;;
esac

if [ -n "$1" ]; then
	case "$1" in
		*start)
			;;
		*)
			msg_usage "(halt|reboot|poweroff) {start}"
			exit 1
			;;
	esac
fi

# Kill all processes
sendsigs

# Write to wtmp file before unmounting /var
halt -w

ACCTOFF=/sbin/accton
[ -x "$ACCTOFF" ] && "$ACCTOFF" off

# Sync clock
/etc/init.d/clock stop

QUOTAOFF=/sbin/quotaoff
[ -x "$QUOTAOFF" ] && action 'Turning off quotas:' "$QUOTAOFF" -a

# Unmount non-/dev tmpfs.
UnmountFilesystems 3 5 \
	'$2 != "/dev" && $3 == "tmpfs" {print $2}' \
	'Unmounting tmpfs filesystem' \
	'Unmounting tmpfs filesystem (retry)'

# Turn off swap, then unmount file systems.
SWAPS=`awk '! /^Filename/ { print $1 }' /proc/swaps`
[ -n "$SWAPS" ] && action 'Turning off swap:' swapoff $SWAPS

# Unmount supermount and autofs*.
UnmountFilesystems 3 5 \
	'$2 != "/" && (($3 == "supermount") || ($3 == "autofs") || ($3 == "autofs4")) {print $2}' \
	'Unmounting automount filesystem' \
	'Unmounting automount filesystem (retry)'

# Unmount loopback stuff first.
UnmountFilesystems 3 5 \
	'$2 != "/" && $1 ~ /^\/dev\/loop/ {print $2}' \
	'Unmounting loopback filesystem' \
	'Unmounting loopback filesystem (retry)'

# Unmount all the rest.
UnmountFilesystems 3 5 \
	'$2 != "/" && $2 !~ /^\/(dev|proc|sys)(\/.*)?$/ && $1 !~ /^none$/ {print $2}' \
	'Unmounting filesystem' \
	'Unmounting filesystem (retry)'

# Turn off encrypted block devices
cryptdisks_exe=/etc/rc.d/scripts/cryptdisks
if [ -x "$cryptdisks_exe" ]; then
	$cryptdisks_exe stop
fi

# Turn off LVM.
/etc/rc.d/scripts/lvm_stop

# Turn off raid.
/etc/rc.d/scripts/raidstop

# Turn off multipath devices.
/etc/rc.d/scripts/multipath_stop

# Turn off early encrypted block devices
cryptdisks_early_exe=/etc/rc.d/scripts/cryptdisks-early
if [ -x "$cryptdisks_early_exe" ]; then
	$cryptdisks_early_exe stop
fi

# Unmount and remount read-only anything that's left mounted.
action 'Remounting remaining filesystems (if any) read-only:' \
	umount -afnr -t noproc,nosysfs,notmpfs,nodevfs,nodevtmpfs,nousbfs,norpc_pipefs,nonfsd
action 'Remounting root filesystem read-only:' mount -n -o remount,ro /

# See if this is a powerfail situation.
UPSCTL=/etc/apcupsd/apccontrol
if [ -x "$UPSCTL" ] && [ -f /etc/apcupsd/powerfail ]; then
	action 'Attempting to turn the UPS off:' "$UPSCTL" killpower
	message='The system is halted'
	command="$HALTCMD"
fi

UPSCTL=/sbin/upsdrvctl
if [ -x "$UPSCTL" ] && [ -f /etc/killpower ]; then
	action 'Attempting to turn the UPS off:' "$UPSCTL" shutdown
	message='The system is halted'
	command="$HALTCMD"
fi

if [ -f /fastboot ]; then
	echo 'On the next boot fsck will be skipped.'
elif [ -f /forcefsck ]; then
	echo 'On the next boot fsck will be forced.'
fi

# Now halt or reboot.
echo "$message"
$command -d -f -i -k
