#!/bin/sh
#
# vgauthd - SAML token and ticketing authentication for VMware
#
# chkconfig: - 81 19
# description: SAML token and ticketing authentication for VMware.
# processname: VGAuthService
# pidfile: /run/vmware/vgauthsvclog_pid.txt

### BEGIN INIT INFO
# Provides:          vgauthd
# Required-Start:    $syslog $local_fs
# Should-Start:
# Required-Stop:     $syslog $local_fs
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: SAML token and ticketing authentication for VMware.
# Description: Service to support SAML token and ticketing authentication for
#              VMware products.
### END INIT INFO

# Do not load RH compatibility interface.
WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/init.d/functions

PIDFILE=/run/vmware/vgauthsvclog_pid.txt
LOCKFILE=/run/lock/subsys/vgauthd
RETVAL=0

check_vmware() {
	if [ ! -x /usr/bin/vmware-checkvm ] || ! /usr/bin/vmware-checkvm > /dev/null 2>&1
	then
		echo "open-vm-tools: not starting as this is not a VMware VM"
		exit 0
	fi
}


start()
{
	check_vmware
	start_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user root -- VGAuthService -b
	RETVAL=$?
	return $RETVAL
}

stop()
{
	stop_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user root -- VGAuthService
	RETVAL=$?
	return $RETVAL
}

restart()
{
	stop
	start
}

reload()
{
	msg_reloading vgauthd
	stop_daemon --pidfile "$PIDFILE" --expect-user root -HUP -- VGAuthService
	RETVAL=$?
	return $RETVAL
} 

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload)
		reload
		;;
	restart)
		restart
		;;
	condstop)
		if [ -e "$LOCKFILE" ]; then
			stop
		fi
		;;
	condrestart)
		if [ -e "$LOCKFILE" ]; then
			restart
		fi
		;;
	condreload)
		if [ -e "$LOCKFILE" ]; then
			reload
		fi
		;;
	status)
		status --pidfile "$PIDFILE" --expect-user root -- VGAuthService
		RETVAL=$?
		;;
	*)
		msg_usage "${0##*/} {start|stop|reload|restart|condstop|condrestart|condreload|status}"
		RETVAL=1
esac

exit $RETVAL
