#! /bin/sh
#
# Preparing video drivers
#
# chkconfig: 345 03 99
# description: Prepare X11 drivers
#
# Do not load RH compatibility interface.
WITHOUT_RC_COMPAT=1

. /etc/init.d/functions


PROGRAM=/usr/sbin/x11presetdrv

RETVAL=0

start() {
    action "Preparing X11 drivers" $PROGRAM
    RETVAL=$?
    return $RETVAL
}

case "$1" in
  start)
  	start
	;;
  status)
	true
	RETVAL=$?
	;;
  stop|condstop|condrestart|condreload|restart|reload)
	RETVAL=1
	;;
  *)
	msg_usage "${0##*/} {start|stop|reload|restart|condstop|condrestart|condreload|status}"
	RETVAL=1
esac

exit $RETVAL
