#!/bin/bash

pickup_defaults
pickup_options

# Assume that we manage all dummy interfaces ourselves. In this
# case dummy0 is only used as a temp name.
# If we see the name already present, the work is over.
iface_exists $NAME && exit
$IP link add $NAME type dummy
