#!/bin/bash

. $SCRIPTDIR/functions-ip

# This file contains supplementary functions for config-ipv4
try_static()
{
	local REALFILE ADDRESSLINE
	if profiled_filename REALFILE "$MYIFACEDIR/ipv4address"; then
		$DENOISE $REALFILE |
		while read ADDRESSLINE; do
			is_yes "$AUTO_BROADCAST" && [ "$ADDRESSLINE" = "${ADDRESSLINE/broadcast/}" ] && \
				ADDRESSLINE="$ADDRESSLINE broadcast +"
			$IP -4 address add dev $NAME $(eval_string $ADDRESSLINE) && print_progress
		done
	fi
	return 0
}

try_ipv4ll()
{
	[ -x "$ZCIP_CLIENT" ] || {
		print_error "$ZCIP_CLIENT does not exist or is not executable. Try installing avahi-autoipd RPM."
		return 1
	}
	if need_detection; then
		if check_eth_link $NAME; then
			print_progress
		else
			print_nack
			return 1
		fi
	fi
	$ZCIP_CLIENT --daemonize --wait $NAME
	local RET=$?
	if [ "$RET" != "0" ]; then
		print_nack
	else
		print_progress
	fi
	return $RET
}

process_ipv4rules()
{
	local OP=${1:?missing 1st arg to $FUNCNAME}
	local REVERSE SRCFILE

	if profiled_filename SRCFILE "$MYIFACEDIR/ipv4rule"; then
		[ "$OP" != "del" ] ||
			REVERSE="|tac"

		eval "$DENOISE \"$SRCFILE\" $REVERSE" |
		while read FIRST REST; do
			case "$FIRST" in
				add)
					[ $OP = "del" ] && FIRST=del
				;;
				del)
					# should we restore deleted rules on iface shutdown?
					 [ $OP = "del" ] && FIRST=add
				;;
				*)
					FIRST="$OP $FIRST"
				;;
			esac
			$IP -4 rule $(eval_string $FIRST $REST)
			print_progress
		done
	fi
}

config_ipv4_routes_rules()
{
	# setup routes
	local OP=${1:?missing 1st arg to $FUNCNAME}
	local SRCFILE SUFFIX
	IPV4ADDRESS=($(get_ipv4_addresses $NAME))

	if profiled_filename SRCFILE "$MYIFACEDIR/ipv4route"; then
		[ "$OP" != "del" ] ||
			REVERSE="|tac"

		eval "$DENOISE \"$SRCFILE\" $REVERSE" |
		while read FIRST REST; do
			# If 'dev' is not specified, add current dev.
			SUFFIX=''
			if ! echo "$FIRST $REST" | grep -Eq '(^|[[:space:]])(throw|unreachable|prohibit|blackhole)[[:space:]]'; then
				echo "$FIRST $REST" | grep -Eq '[[:space:]]dev[[:space:]]' || SUFFIX="dev $NAME"
			fi
			# If operation is not specified, use 'append'.
			case "$FIRST" in
				add|change|append|replace)
					[ $OP = "del" ] && FIRST=del
				;;
				del)
					# should we restore deleted rules on iface shutdown?
					[ $OP = "del" ] && FIRST=add
				;;
				*)
					[ "$OP" = "add" ] && FIRST="append $FIRST" || FIRST="$OP $FIRST"
				;;
			esac
			$IP -4 route $(eval_string $FIRST $REST $SUFFIX)
			print_progress
		done
	fi

	# Setup rules only after routes are Ok, so that route tables are
	# already populated when rule starts routing traffic to them.
	process_ipv4rules $OP
}

get_ipv4_addresses()
{
    local NAME=${1:?missing 1st argument to $FUNCNAME}
    # FIXME should we parse it by more complex regexp?
    printf "$($IP -4 addr show dev $NAME 2>/dev/null|grep -ose "\binet[[:space:]]\+[0-9.]\+"|cut -f2 -d" ")"
}
