.TH "Sender" 3 "Fri May 3 2024" "My_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sender
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAck\fP (bool ok)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSender\fP class\&. Can be used to send a command to the server\&. The receiver will acknowledge the command by calling \fBAck()\fP\&.  
.PP
Definition at line 8 of file with_uml\&.c\&.
.SH "Member Function Documentation"
.PP 
.SS "void Sender::Ack (bool ok)"
Acknowledgment from server 

.SH "Author"
.PP 
Generated automatically by Doxygen for My_Project from the source code\&.
