#!/bin/bash

removelog="/var/log/remove.log"

if [ $# -eq 0 ] ; then
	echo "Использование: $0 [-s] список файлов или каталогов" >&2
	exit 1
fi

if [ "$1" = "-s" ] ; then
	# Операция без журналирования
	shift
else
	#echo "$(date): ${USER}: $@" >> $removelog
	logger -t logrm "${USER: -LOGNAME}: $*"
fi

/bin/rm "$@"

exit 0