#!/bin/sh

. /etc/control.d/functions

BINARY=/usr/bin/at

new_fmode public 2711 root crontab
new_fmode restricted 700 root root
new_fmode atdaemon 2711 root atdaemon

new_help public "Any user can execute $BINARY"
new_help restricted "Only root can execute $BINARY"
new_help atdaemon "Compatibility mode, should not be used"

# Backwards compatibility
test "$*" = atdaemon && set - public

control_fmode "$BINARY" "$*" || exit 1
