#! /bin/sh

. /etc/control.d/functions-local-policy

CONFIG=/etc/autofs.conf

new_help disabled 'Do not browse autofs target mountpoints'
new_help enabled 'Browse autofs target mountpoints'
new_help default 'Do not browse autofs target mountpoints'

new_subst default \
	'^\s*#\s*browse_mode\s*=\s*(no|yes)\s*' \
	's/^\s*#\?\(\s*browse_mode\)\s*=.*/#\1 = no/'

new_subst enabled \
	'^\s*browse_mode\s*=\s*yes\s*' \
	's/^\s*#\?\(\s*browse_mode\)\s\=.*/\1 = yes/'

new_subst disabled \
	'^\s*browse_mode\s*=\s*no\s*' \
	's/^\s*#\?\(\s*browse_mode\)\s*=.*/\1 = no/'

new_summary 'Browse autofs target mountpoints'

control_subst_with_file_check "$CONFIG" "$*" "default enabled disabled"

