#!/bin/sh

. /etc/control.d/functions

CONFIG_COMMON=/etc/pam.d/system-auth-common
CONFIG_SYSTEM=/etc/pam.d/system-auth

if [ -f "$CONFIG_COMMON" ]; then
	CONFIG="$CONFIG_COMMON"
else
	CONFIG="$(readlink -e "$CONFIG_SYSTEM")" ||
	CONFIG="$CONFIG_SYSTEM"
fi

new_summary "pam_canonicalize_user support in system authentication"

new_subst enabled \
        '^-?auth[[:space:]]+(optional|required)[[:space:]]+pam_canonicalize_user.so[[:space:]]*$' \
        's,^#[#[:space:]]*\(-\?auth[[:space:]]\+\(optional\|required\)[[:space:]]\+pam_canonicalize_user.so[[:space:]]*\)$,\1,'
new_subst disabled \
        '^#[#[:space:]]*-?auth[[:space:]]+(optional|required)[[:space:]]+pam_canonicalize_user.so[[:space:]]*$' \
        's,^\(-\?auth[[:space:]]\+\(optional\|required\)[[:space:]]\+pam_canonicalize_user.so[[:space:]]*\)$,#\1,'

new_help enabled "Enable pam_canonicalize_user support"
new_help disabled "Disable pam_canonicalize_user support"

control_subst "$CONFIG" "$*"
