#! /bin/sh

. /etc/control.d/functions-local-policy

CONFIG=/etc/openssh/sshd_config

new_subst disabled \
	'^GSSAPIAuthentication[[:space:]]+no' \
	's/^#\?\(GSSAPIAuthentication\)[[:space:]]\+.*/\1 no/'

new_subst enabled \
	'^GSSAPIAuthentication[[:space:]]+yes' \
	's/^#\?\(GSSAPIAuthentication\)[[:space:]]\+.*/\1 yes/'

new_subst default \
	'^#GSSAPIAuthentication[[:space:]]+no' \
	's/^#\?\(GSSAPIAuthentication\)[[:space:]]\+.*/#\1 no/'


new_help disabled 'Disable GSSAPI authentication (Single Sign-On feature)'
new_help enabled 'Use GSSAPI authentication (Single Sign-On feature)'
new_help default 'Disable GSSAPI authentication (Single Sign-On feature)'

new_summary 'GSSAPI authentication mechanism in SSHD'

control_subst_with_file_check "$CONFIG" "$*" "disabled enabled default"

