#!/bin/sh

. /etc/control.d/functions

BINARY=/usr/bin/dumpcap

new_fmode public 4711 root root
new_fmode relaxed 711 root root
new_fmode netadmin 4710 root netadmin
new_fmode restricted 700 root root

new_help public "Any user can execute $BINARY, traffic capture enabled"
new_help relaxed "Any user can execute $BINARY, traffic capture disabled"
new_help netadmin "Only \"netadmin\" group members can execute $BINARY, traffic capture enabled"
new_help restricted "Only root can execute $BINARY"

control_fmode "$BINARY" "$*" || exit 1
