#!/bin/sh

. /etc/control.d/functions

BINARY=/usr/bin/write

new_summary "write utility for sending messages to another user"

new_fmode public 2711 root tty
new_fmode restricted 700 root root

new_help public "Any user can execute $BINARY"
new_help restricted "Only root can execute $BINARY"

control_fmode "$BINARY" "$*" || exit 1
