#!/bin/sh

. /etc/control.d/functions

for BINARY in /usr/bin/Xorg /usr/X11R6/bin/Xorg /usr/X11R6/bin/XFree86; do
	[ -f "$BINARY" ] && break || BINARY=
done
[ -n "$BINARY" ] || BINARY=/usr/bin/Xorg

new_fmode public 4711 root root
new_fmode xgrp 4710 root xgrp
new_fmode restricted 700 root root

new_help public "Any user can execute $BINARY"
new_help xgrp "Only \"xgrp\" group members can execute $BINARY"
new_help restricted "Only root can execute $BINARY"

control_fmode "$BINARY" "$*" || exit 1
