.TH "/home/st/REPOBARE/_repo/NBash/.arb/util/doxygen.ram/.grot/exa_2.d/exa_2.d/poroject2.ws/doxygen_c.h" 3 "Thu May 9 2024" "Version 5" "My_Project__" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/st/REPOBARE/_repo/NBash/.arb/util/doxygen.ram/.grot/exa_2.d/exa_2.d/poroject2.ws/doxygen_c.h \- File containing example of doxygen usage for quick reference\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <systemheader1\&.h>\fP
.br
\fC#include <systemheader2\&.h>\fP
.br
\fC#include <box/header1\&.h>\fP
.br
\fC#include <box/header2\&.h>\fP
.br
\fC#include 'local_header1\&.h'\fP
.br
\fC#include 'local_header2\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBBoxStruct_struct\fP"
.br
.RI "Use brief, otherwise the index won't have a brief explanation\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBBoxEnum_enum\fP \fBBoxEnum\fP"
.br
.RI "Use brief, otherwise the index won't have a brief explanation\&. "
.ti -1c
.RI "typedef struct \fBBoxStruct_struct\fP \fBBoxStruct\fP"
.br
.RI "Use brief, otherwise the index won't have a brief explanation\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBoxEnum_enum\fP { \fBBOXENUM_FIRST\fP, \fBBOXENUM_SECOND\fP, \fBBOXENUM_ETC\fP, \fBBOXENUM_FIRST\fP, \fBBOXENUM_SECOND\fP, \fBBOXENUM_ETC\fP, \fBBOXENUM_FIRST\fP, \fBBOXENUM_SECOND\fP, \fBBOXENUM_ETC\fP, \fBBOXENUM_FIRST\fP, \fBBOXENUM_SECOND\fP, \fBBOXENUM_ETC\fP }"
.br
.RI "Use brief, otherwise the index won't have a brief explanation\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "BOXEXPORT \fBBoxStruct\fP * \fBBox_The_Function_Name\fP (BoxParamType1 param1, BoxParamType2 param2)"
.br
.RI "Example showing how to document a function with Doxygen\&. "
.ti -1c
.RI "BOXEXPORT void * \fBBox_The_Second_Function\fP (void)"
.br
.RI "A simple stub function to show how links do work\&. "
.ti -1c
.RI "BOXEXPORT void \fBBox_The_Last_One\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File containing example of doxygen usage for quick reference\&. 


.PP
\fBAuthor\fP
.RS 4
My Self 
.RE
.PP
\fBDate\fP
.RS 4
9 Sep 2012
.RE
.PP
Here typically goes a more extensive explanation of what the header defines\&. Doxygens tags are words preceeded by either a backslash \\ or by an at symbol @\&. 
.PP
\fBSee also\fP
.RS 4
http://www.stack.nl/~dimitri/doxygen/docblocks.html 
.PP
http://www.stack.nl/~dimitri/doxygen/commands.html 
.RE
.PP

.PP
Definition in file \fBdoxygen_c\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBBoxEnum_enum\fP BoxEnum"

.PP
Use brief, otherwise the index won't have a brief explanation\&. Detailed explanation\&. 
.SS "typedef struct \fBBoxStruct_struct\fP \fBBoxStruct\fP"

.PP
Use brief, otherwise the index won't have a brief explanation\&. Detailed explanation\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum BoxEnum_enum"

.PP
Use brief, otherwise the index won't have a brief explanation\&. Detailed explanation\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBOXENUM_FIRST \fP\fP
Some documentation for first\&. 
.TP
\fB\fIBOXENUM_SECOND \fP\fP
Some documentation for second\&. 
.TP
\fB\fIBOXENUM_ETC \fP\fP
Etc\&. 
.TP
\fB\fIBOXENUM_FIRST \fP\fP
Some documentation for first\&. 
.TP
\fB\fIBOXENUM_SECOND \fP\fP
Some documentation for second\&. 
.TP
\fB\fIBOXENUM_ETC \fP\fP
Etc\&. 
.TP
\fB\fIBOXENUM_FIRST \fP\fP
Some documentation for first\&. 
.TP
\fB\fIBOXENUM_SECOND \fP\fP
Some documentation for second\&. 
.TP
\fB\fIBOXENUM_ETC \fP\fP
Etc\&. 
.PP
Definition at line 50 of file doxygen_c\&.h\&.
.SH "Function Documentation"
.PP 
.SS "BOXEXPORT \fBBoxStruct\fP* Box_The_Function_Name (BoxParamType1 param1, BoxParamType2 param2)"

.PP
Example showing how to document a function with Doxygen\&. Description of what the function does\&. This part may refer to the parameters of the function, like \fCparam1\fP or \fCparam2\fP\&. A word of code can also be inserted like \fCthis\fP which is equivalent to \fCthis\fP and can be useful to say that the function returns a \fCvoid\fP or an \fCint\fP\&. If you want to have more than one word in typewriter font, then just use <tt>\&. We can also include text verbatim, 
.PP
.nf
like this
.fi
.PP
 Sometimes it is also convenient to include an example of usage: 
.PP
.nf
BoxStruct *out = Box_The_Function_Name(param1, param2);
printf("something\&.\&.\&.\n");

.fi
.PP
 Or, 
.PP
.nf
pyval = python_func(arg1, arg2)
print pyval

.fi
.PP
 when the language is not the one used in the current source file (but \fBbe careful\fP as this may be supported only by recent versions of Doxygen)\&. By the way, \fBthis is how you write bold text\fP or, if it is just one word, then you can just do \fBthis\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIparam1\fP Description of the first parameter of the function\&. 
.br
\fIparam2\fP The second one, which follows \fCparam1\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Describe what the function returns\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBBox_The_Second_Function\fP 
.PP
\fBBox_The_Last_One\fP 
.PP
http://website/ 
.RE
.PP
\fBNote\fP
.RS 4
Something to note\&. 
.RE
.PP
\fBWarning\fP
.RS 4
Warning\&. 
.RE
.PP

.SS "BOXEXPORT void Box_The_Last_One (void)"
Brief can be omitted\&. If you configure Doxygen with \fCJAVADOC_AUTOBRIEF=YES\fP, then the first Line of the comment is used instead\&. In this function this would be as if 
.PP
.nf
@brief Brief can be omitted. 
.fi
.PP
 was used instead\&. 
.SS "BOXEXPORT void* Box_The_Second_Function (void)"

.PP
A simple stub function to show how links do work\&. Links are generated automatically for webpages (like http://www.google.co.uk) and for structures, like \fBBoxStruct_struct\fP\&. For typedef-ed types use \fBBoxStruct\fP\&. For functions, automatic links are generated when the parenthesis () follow the name of the function, like \fBBox_The_Function_Name()\fP\&. Alternatively, you can use \fBBox_The_Function_Name\fP\&. 
.PP
\fBReturns\fP
.RS 4
\fCNULL\fP is always returned\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My_Project__ from the source code\&.
