.TH "/home/st/REPOBARE/_repo/NBash/.arb/util/doxygen.ram/.grot/exa.d/wolf-u.li.ru.d/poroject.ws/main.sh" 3 "Fri May 3 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/st/REPOBARE/_repo/NBash/.arb/util/doxygen.ram/.grot/exa.d/wolf-u.li.ru.d/poroject.ws/main.sh \- Runs the cooles things in the world\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Runs the cooles things in the world\&. 


.PP
\fBAuthor\fP
.RS 4
Uli Wolf 
.RE
.PP
\fBDate\fP
.RS 4
2016-06-08 
.RE
.PP
\fBCopyright\fP
.RS 4
Released under the WTFPL
.RE
.PP
This script provides the required code to run code that is cooler than anybody elses code 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
