#!/bin/sh
#
# /etc/rc.d/scripts/framebuffer - run once at boot time from rc.sysinit

WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/init.d/functions

# Parse framebuffer config.
SourceIfNotEmpty /etc/sysconfig/framebuffer && ! is_no "$ENABLE" || exit 0

# Load framebuffer module.
if [ -n "$MODULE" ]; then
	action "Loading module $MODULE:" /sbin/modprobe "$MODULE" $ARGS 2>/dev/null
fi

# fbset program
FBSET=/usr/sbin/fbset

# Setup videomode if defined
if [ -n "$MODE" ] && [ -x "$FBSET" ]; then
	action "Setting framebuffer device settings:" "$FBSET" -a "$MODE"
fi
