#!/bin/sh

VGCHANGE=/sbin/vgchange
if [ -x "$VGCHANGE" ] && [ -s /etc/lvm/lvm.conf ] &&
   grep -E -qs '^ *([^ ]+ +){3}dm-[0-9]+$' /proc/partitions; then
	WITHOUT_RC_COMPAT=1
	. /etc/init.d/functions

	action "Turning off LVM:" "$VGCHANGE" -a n
fi
