#!/bin/sh

MODPROBE=/sbin/modprobe
VGSCAN=/sbin/vgscan
VGCHANGE=/sbin/vgchange
if [ -e "$VGCHANGE" ] && [ -e "$VGSCAN" ] && [ -s /etc/lvm/lvm.conf ] && [ -c /dev/mapper/control ]; then
	WITHOUT_RC_COMPAT=1
	. /etc/init.d/functions

	"$MODPROBE" dm-mod >/dev/null 2>&1
	"$VGSCAN" --mknodes >/dev/null 2>&1
	action "Setting up LVM2:" "$VGCHANGE" -a y
fi
